// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TWMS.Infrastructure.Persistence.DBContext;

#nullable disable

namespace TWMS.Infrastructure.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230527221913_updatedModelAndData")]
    partial class updatedModelAndData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TWMS.Domain.Models.Customer.CustomerAddress", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AreaLocality")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BuildingNumber")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Landmark")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("State_Province")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StreetName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Zip_PostalCode")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("CustomerAddresses");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("ef73f0aa-8055-4314-9969-7f31c1845950"),
                            AreaLocality = "Area 1",
                            BuildingNumber = 78,
                            City = "City 1",
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 17, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5639), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 5, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5636), new TimeSpan(0, 1, 0, 0, 0)),
                            Landmark = "Landmark 1",
                            ModifiedBy = "John Doe",
                            State_Province = "State 1",
                            StreetName = "Street 1",
                            Zip_PostalCode = 66430
                        },
                        new
                        {
                            CustomerId = new Guid("11af2960-8a50-4979-a9c3-b32bc68eba38"),
                            AreaLocality = "Area 2",
                            BuildingNumber = 60,
                            City = "City 2",
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 25, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5656), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 14, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5654), new TimeSpan(0, 1, 0, 0, 0)),
                            Landmark = "Landmark 2",
                            ModifiedBy = "John Doe",
                            State_Province = "State 2",
                            StreetName = "Street 2",
                            Zip_PostalCode = 34548
                        },
                        new
                        {
                            CustomerId = new Guid("a5f3017d-9f83-44fd-9f95-caa571f76abb"),
                            AreaLocality = "Area 3",
                            BuildingNumber = 16,
                            City = "City 3",
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 16, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5665), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 18, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5663), new TimeSpan(0, 1, 0, 0, 0)),
                            Landmark = "Landmark 3",
                            ModifiedBy = "John Doe",
                            State_Province = "State 3",
                            StreetName = "Street 3",
                            Zip_PostalCode = 83522
                        },
                        new
                        {
                            CustomerId = new Guid("e24303f7-293e-467b-b236-13e50f3d90d2"),
                            AreaLocality = "Area 4",
                            BuildingNumber = 42,
                            City = "City 4",
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 2, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5673), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 5, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5671), new TimeSpan(0, 1, 0, 0, 0)),
                            Landmark = "Landmark 4",
                            ModifiedBy = "John Doe",
                            State_Province = "State 4",
                            StreetName = "Street 4",
                            Zip_PostalCode = 16040
                        },
                        new
                        {
                            CustomerId = new Guid("f129c122-d315-473c-b641-370bc022b031"),
                            AreaLocality = "Area 5",
                            BuildingNumber = 3,
                            City = "City 5",
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 20, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5681), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 26, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5679), new TimeSpan(0, 1, 0, 0, 0)),
                            Landmark = "Landmark 5",
                            ModifiedBy = "John Doe",
                            State_Province = "State 5",
                            StreetName = "Street 5",
                            Zip_PostalCode = 78123
                        },
                        new
                        {
                            CustomerId = new Guid("bbd4474e-7adc-4fbb-ba9e-428c51d88531"),
                            AreaLocality = "Area 6",
                            BuildingNumber = 67,
                            City = "City 6",
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 6, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5690), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 15, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5688), new TimeSpan(0, 1, 0, 0, 0)),
                            Landmark = "Landmark 6",
                            ModifiedBy = "John Doe",
                            State_Province = "State 6",
                            StreetName = "Street 6",
                            Zip_PostalCode = 66278
                        },
                        new
                        {
                            CustomerId = new Guid("20f09330-8204-4e3a-b343-fd0d6a3ccfa7"),
                            AreaLocality = "Area 7",
                            BuildingNumber = 13,
                            City = "City 7",
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 18, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5754), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 26, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5751), new TimeSpan(0, 1, 0, 0, 0)),
                            Landmark = "Landmark 7",
                            ModifiedBy = "John Doe",
                            State_Province = "State 7",
                            StreetName = "Street 7",
                            Zip_PostalCode = 33555
                        },
                        new
                        {
                            CustomerId = new Guid("9556a60d-fbbe-4819-937c-832a8b66b6b8"),
                            AreaLocality = "Area 8",
                            BuildingNumber = 11,
                            City = "City 8",
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 1, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5763), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 23, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5761), new TimeSpan(0, 1, 0, 0, 0)),
                            Landmark = "Landmark 8",
                            ModifiedBy = "John Doe",
                            State_Province = "State 8",
                            StreetName = "Street 8",
                            Zip_PostalCode = 31658
                        },
                        new
                        {
                            CustomerId = new Guid("2cf1decd-666b-4d39-bb31-78e9fdc432ed"),
                            AreaLocality = "Area 9",
                            BuildingNumber = 84,
                            City = "City 9",
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 5, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5772), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 16, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5770), new TimeSpan(0, 1, 0, 0, 0)),
                            Landmark = "Landmark 9",
                            ModifiedBy = "John Doe",
                            State_Province = "State 9",
                            StreetName = "Street 9",
                            Zip_PostalCode = 16603
                        },
                        new
                        {
                            CustomerId = new Guid("a3c4bd1c-081a-4a99-8ca4-886208a118d3"),
                            AreaLocality = "Area 10",
                            BuildingNumber = 45,
                            City = "City 10",
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 4, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5782), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 13, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5779), new TimeSpan(0, 1, 0, 0, 0)),
                            Landmark = "Landmark 10",
                            ModifiedBy = "John Doe",
                            State_Province = "State 10",
                            StreetName = "Street 10",
                            Zip_PostalCode = 66746
                        });
                });

            modelBuilder.Entity("TWMS.Domain.Models.Customer.Customers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CustomerAddressCustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAddressCustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef73f0aa-8055-4314-9969-7f31c1845950"),
                            Birthday = new DateTime(1972, 5, 27, 23, 19, 13, 596, DateTimeKind.Local).AddTicks(5329),
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 16, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5315), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 3, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5300), new TimeSpan(0, 1, 0, 0, 0)),
                            EmailAddress = "customer1@example.com",
                            FullName = "Customer 1",
                            ModifiedBy = "John Doe",
                            PhoneNo = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("11af2960-8a50-4979-a9c3-b32bc68eba38"),
                            Birthday = new DateTime(1994, 5, 27, 23, 19, 13, 596, DateTimeKind.Local).AddTicks(5344),
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 7, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5340), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 3, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5338), new TimeSpan(0, 1, 0, 0, 0)),
                            EmailAddress = "customer2@example.com",
                            FullName = "Customer 2",
                            ModifiedBy = "John Doe",
                            PhoneNo = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("a5f3017d-9f83-44fd-9f95-caa571f76abb"),
                            Birthday = new DateTime(1994, 5, 27, 23, 19, 13, 596, DateTimeKind.Local).AddTicks(5354),
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 6, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5352), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 6, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5349), new TimeSpan(0, 1, 0, 0, 0)),
                            EmailAddress = "customer3@example.com",
                            FullName = "Customer 3",
                            ModifiedBy = "John Doe",
                            PhoneNo = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("e24303f7-293e-467b-b236-13e50f3d90d2"),
                            Birthday = new DateTime(1995, 5, 27, 23, 19, 13, 596, DateTimeKind.Local).AddTicks(5364),
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 5, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5361), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 22, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5359), new TimeSpan(0, 1, 0, 0, 0)),
                            EmailAddress = "customer4@example.com",
                            FullName = "Customer 4",
                            ModifiedBy = "John Doe",
                            PhoneNo = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("f129c122-d315-473c-b641-370bc022b031"),
                            Birthday = new DateTime(1964, 5, 27, 23, 19, 13, 596, DateTimeKind.Local).AddTicks(5374),
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 25, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5371), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 4, 28, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5369), new TimeSpan(0, 1, 0, 0, 0)),
                            EmailAddress = "customer5@example.com",
                            FullName = "Customer 5",
                            ModifiedBy = "John Doe",
                            PhoneNo = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("bbd4474e-7adc-4fbb-ba9e-428c51d88531"),
                            Birthday = new DateTime(1975, 5, 27, 23, 19, 13, 596, DateTimeKind.Local).AddTicks(5385),
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 15, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5383), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 9, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5380), new TimeSpan(0, 1, 0, 0, 0)),
                            EmailAddress = "customer6@example.com",
                            FullName = "Customer 6",
                            ModifiedBy = "John Doe",
                            PhoneNo = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("20f09330-8204-4e3a-b343-fd0d6a3ccfa7"),
                            Birthday = new DateTime(2001, 5, 27, 23, 19, 13, 596, DateTimeKind.Local).AddTicks(5397),
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 14, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5394), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 12, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5392), new TimeSpan(0, 1, 0, 0, 0)),
                            EmailAddress = "customer7@example.com",
                            FullName = "Customer 7",
                            ModifiedBy = "John Doe",
                            PhoneNo = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("9556a60d-fbbe-4819-937c-832a8b66b6b8"),
                            Birthday = new DateTime(1993, 5, 27, 23, 19, 13, 596, DateTimeKind.Local).AddTicks(5407),
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 22, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5404), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 15, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5402), new TimeSpan(0, 1, 0, 0, 0)),
                            EmailAddress = "customer8@example.com",
                            FullName = "Customer 8",
                            ModifiedBy = "John Doe",
                            PhoneNo = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("2cf1decd-666b-4d39-bb31-78e9fdc432ed"),
                            Birthday = new DateTime(1981, 5, 27, 23, 19, 13, 596, DateTimeKind.Local).AddTicks(5417),
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 11, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5415), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 19, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5412), new TimeSpan(0, 1, 0, 0, 0)),
                            EmailAddress = "customer9@example.com",
                            FullName = "Customer 9",
                            ModifiedBy = "John Doe",
                            PhoneNo = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("a3c4bd1c-081a-4a99-8ca4-886208a118d3"),
                            Birthday = new DateTime(1976, 5, 27, 23, 19, 13, 596, DateTimeKind.Local).AddTicks(5427),
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 12, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5424), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 11, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(5422), new TimeSpan(0, 1, 0, 0, 0)),
                            EmailAddress = "customer10@example.com",
                            FullName = "Customer 10",
                            ModifiedBy = "John Doe",
                            PhoneNo = "1234567890"
                        });
                });

            modelBuilder.Entity("TWMS.Domain.Models.Order.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 7, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6382), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = new Guid("ef73f0aa-8055-4314-9969-7f31c1845950"),
                            DateModified = new DateTimeOffset(new DateTime(2023, 4, 30, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6378), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            ModifiedBy = "John Doe",
                            TotalCost = 89549m
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 17, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6453), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = new Guid("ef73f0aa-8055-4314-9969-7f31c1845950"),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 21, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6450), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            ModifiedBy = "John Doe",
                            TotalCost = 56514m
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 10, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6480), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = new Guid("11af2960-8a50-4979-a9c3-b32bc68eba38"),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 26, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6478), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            ModifiedBy = "John Doe",
                            TotalCost = 148860m
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 3, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6508), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = new Guid("11af2960-8a50-4979-a9c3-b32bc68eba38"),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 10, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6506), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            ModifiedBy = "John Doe",
                            TotalCost = 50180m
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 22, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6534), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = new Guid("a5f3017d-9f83-44fd-9f95-caa571f76abb"),
                            DateModified = new DateTimeOffset(new DateTime(2023, 4, 30, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6532), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            ModifiedBy = "John Doe",
                            TotalCost = 54373m
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 20, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6562), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = new Guid("a5f3017d-9f83-44fd-9f95-caa571f76abb"),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 24, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6559), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            ModifiedBy = "John Doe",
                            TotalCost = 65295m
                        },
                        new
                        {
                            Id = 19,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 4, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6587), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = new Guid("e24303f7-293e-467b-b236-13e50f3d90d2"),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 1, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6584), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            ModifiedBy = "John Doe",
                            TotalCost = 97408m
                        },
                        new
                        {
                            Id = 22,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 4, 28, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6612), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = new Guid("e24303f7-293e-467b-b236-13e50f3d90d2"),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 20, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6609), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            ModifiedBy = "John Doe",
                            TotalCost = 38324m
                        },
                        new
                        {
                            Id = 25,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 23, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6637), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = new Guid("f129c122-d315-473c-b641-370bc022b031"),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 1, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6634), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            ModifiedBy = "John Doe",
                            TotalCost = 60952m
                        },
                        new
                        {
                            Id = 28,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 18, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6714), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = new Guid("f129c122-d315-473c-b641-370bc022b031"),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 10, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6711), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            ModifiedBy = "John Doe",
                            TotalCost = 228450m
                        },
                        new
                        {
                            Id = 31,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 4, 29, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6740), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = new Guid("bbd4474e-7adc-4fbb-ba9e-428c51d88531"),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 24, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6737), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            ModifiedBy = "John Doe",
                            TotalCost = 37024m
                        },
                        new
                        {
                            Id = 34,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 4, 28, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6765), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = new Guid("bbd4474e-7adc-4fbb-ba9e-428c51d88531"),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 18, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6762), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            ModifiedBy = "John Doe",
                            TotalCost = 50308m
                        },
                        new
                        {
                            Id = 37,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 2, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6790), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = new Guid("20f09330-8204-4e3a-b343-fd0d6a3ccfa7"),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 18, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6787), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            ModifiedBy = "John Doe",
                            TotalCost = 89644m
                        },
                        new
                        {
                            Id = 40,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 12, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6815), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = new Guid("20f09330-8204-4e3a-b343-fd0d6a3ccfa7"),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 16, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6812), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            ModifiedBy = "John Doe",
                            TotalCost = 52773m
                        },
                        new
                        {
                            Id = 43,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 25, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6840), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = new Guid("9556a60d-fbbe-4819-937c-832a8b66b6b8"),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 16, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6837), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            ModifiedBy = "John Doe",
                            TotalCost = 112409m
                        },
                        new
                        {
                            Id = 46,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 25, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6865), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = new Guid("9556a60d-fbbe-4819-937c-832a8b66b6b8"),
                            DateModified = new DateTimeOffset(new DateTime(2023, 4, 29, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6862), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            ModifiedBy = "John Doe",
                            TotalCost = 149563m
                        },
                        new
                        {
                            Id = 49,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 20, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6890), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = new Guid("2cf1decd-666b-4d39-bb31-78e9fdc432ed"),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 3, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6887), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            ModifiedBy = "John Doe",
                            TotalCost = 56883m
                        },
                        new
                        {
                            Id = 52,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 3, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6916), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = new Guid("2cf1decd-666b-4d39-bb31-78e9fdc432ed"),
                            DateModified = new DateTimeOffset(new DateTime(2023, 4, 29, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6914), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            ModifiedBy = "John Doe",
                            TotalCost = 44406m
                        },
                        new
                        {
                            Id = 55,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 8, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6941), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = new Guid("a3c4bd1c-081a-4a99-8ca4-886208a118d3"),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 23, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6938), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            ModifiedBy = "John Doe",
                            TotalCost = 49265m
                        },
                        new
                        {
                            Id = 58,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 18, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6965), new TimeSpan(0, 1, 0, 0, 0)),
                            CustomerId = new Guid("a3c4bd1c-081a-4a99-8ca4-886208a118d3"),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 3, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6962), new TimeSpan(0, 1, 0, 0, 0)),
                            IsActive = true,
                            ModifiedBy = "John Doe",
                            TotalCost = 148401m
                        });
                });

            modelBuilder.Entity("TWMS.Domain.Models.Order.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CustomersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomersId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 25, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6392), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 22, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6389), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 1,
                            Price = 403m,
                            ProductId = 1,
                            Quantity = 31
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 6, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6407), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 2, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6404), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 1,
                            Price = 301m,
                            ProductId = 1,
                            Quantity = 256
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 3, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6461), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 24, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6459), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 4,
                            Price = 146m,
                            ProductId = 2,
                            Quantity = 193
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 2, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6469), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 8, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6467), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 4,
                            Price = 368m,
                            ProductId = 2,
                            Quantity = 77
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 6, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6489), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 4, 28, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6486), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 7,
                            Price = 208m,
                            ProductId = 1,
                            Quantity = 245
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 13, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6496), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 4, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6493), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 7,
                            Price = 356m,
                            ProductId = 1,
                            Quantity = 275
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 1, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6516), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 22, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6513), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 10,
                            Price = 475m,
                            ProductId = 2,
                            Quantity = 80
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 14, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6523), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 3, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6521), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 10,
                            Price = 435m,
                            ProductId = 2,
                            Quantity = 28
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 15, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6542), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 18, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6540), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 13,
                            Price = 143m,
                            ProductId = 1,
                            Quantity = 222
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 14, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6549), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 14, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6547), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 13,
                            Price = 187m,
                            ProductId = 1,
                            Quantity = 121
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 13, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6569), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 25, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6567), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 16,
                            Price = 273m,
                            ProductId = 2,
                            Quantity = 191
                        },
                        new
                        {
                            Id = 18,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 24, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6576), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 15, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6574), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 16,
                            Price = 411m,
                            ProductId = 2,
                            Quantity = 32
                        },
                        new
                        {
                            Id = 20,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 22, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6594), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 6, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6592), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 19,
                            Price = 420m,
                            ProductId = 1,
                            Quantity = 66
                        },
                        new
                        {
                            Id = 21,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 23, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6601), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 4, 29, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6599), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 19,
                            Price = 281m,
                            ProductId = 1,
                            Quantity = 248
                        },
                        new
                        {
                            Id = 23,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 24, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6619), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 22, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6616), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 22,
                            Price = 254m,
                            ProductId = 2,
                            Quantity = 28
                        },
                        new
                        {
                            Id = 24,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 23, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6626), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 5, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6624), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 22,
                            Price = 459m,
                            ProductId = 2,
                            Quantity = 68
                        },
                        new
                        {
                            Id = 26,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 2, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6645), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 23, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6642), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 25,
                            Price = 312m,
                            ProductId = 1,
                            Quantity = 88
                        },
                        new
                        {
                            Id = 27,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 1, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6652), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 12, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6650), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 25,
                            Price = 212m,
                            ProductId = 1,
                            Quantity = 158
                        },
                        new
                        {
                            Id = 29,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 18, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6721), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 5, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6719), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 28,
                            Price = 467m,
                            ProductId = 2,
                            Quantity = 213
                        },
                        new
                        {
                            Id = 30,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 24, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6729), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 2, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6726), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 28,
                            Price = 459m,
                            ProductId = 2,
                            Quantity = 281
                        },
                        new
                        {
                            Id = 32,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 4, 28, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6747), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 1, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6745), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 31,
                            Price = 236m,
                            ProductId = 1,
                            Quantity = 41
                        },
                        new
                        {
                            Id = 33,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 1, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6754), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 17, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6752), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 31,
                            Price = 129m,
                            ProductId = 1,
                            Quantity = 212
                        },
                        new
                        {
                            Id = 35,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 7, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6772), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 16, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6770), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 34,
                            Price = 234m,
                            ProductId = 2,
                            Quantity = 122
                        },
                        new
                        {
                            Id = 36,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 4, 29, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6779), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 17, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6777), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 34,
                            Price = 320m,
                            ProductId = 2,
                            Quantity = 68
                        },
                        new
                        {
                            Id = 38,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 20, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6797), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 18, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6795), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 37,
                            Price = 284m,
                            ProductId = 1,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 39,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 2, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6804), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 13, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6802), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 37,
                            Price = 308m,
                            ProductId = 1,
                            Quantity = 268
                        },
                        new
                        {
                            Id = 41,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 11, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6822), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 4, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6820), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 40,
                            Price = 161m,
                            ProductId = 2,
                            Quantity = 69
                        },
                        new
                        {
                            Id = 42,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 11, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6829), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 18, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6827), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 40,
                            Price = 217m,
                            ProductId = 2,
                            Quantity = 192
                        },
                        new
                        {
                            Id = 44,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 13, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6847), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 3, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6845), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 43,
                            Price = 360m,
                            ProductId = 1,
                            Quantity = 75
                        },
                        new
                        {
                            Id = 45,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 25, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6855), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 4, 29, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6852), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 43,
                            Price = 383m,
                            ProductId = 1,
                            Quantity = 223
                        },
                        new
                        {
                            Id = 47,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 24, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6872), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 5, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6870), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 46,
                            Price = 331m,
                            ProductId = 2,
                            Quantity = 298
                        },
                        new
                        {
                            Id = 48,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 23, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6880), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 12, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6877), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 46,
                            Price = 175m,
                            ProductId = 2,
                            Quantity = 291
                        },
                        new
                        {
                            Id = 50,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 5, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6897), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 14, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6895), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 49,
                            Price = 183m,
                            ProductId = 1,
                            Quantity = 133
                        },
                        new
                        {
                            Id = 51,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 2, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6904), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 6, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6902), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 49,
                            Price = 226m,
                            ProductId = 1,
                            Quantity = 144
                        },
                        new
                        {
                            Id = 53,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 16, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6923), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 7, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6921), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 52,
                            Price = 256m,
                            ProductId = 2,
                            Quantity = 42
                        },
                        new
                        {
                            Id = 54,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 16, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6930), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 4, 28, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6928), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 52,
                            Price = 213m,
                            ProductId = 2,
                            Quantity = 158
                        },
                        new
                        {
                            Id = 56,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 4, 29, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6948), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 18, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6946), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 55,
                            Price = 215m,
                            ProductId = 1,
                            Quantity = 37
                        },
                        new
                        {
                            Id = 57,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 9, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6955), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 22, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6953), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 55,
                            Price = 270m,
                            ProductId = 1,
                            Quantity = 153
                        },
                        new
                        {
                            Id = 59,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 4, 28, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6972), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 4, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6970), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 58,
                            Price = 437m,
                            ProductId = 2,
                            Quantity = 269
                        },
                        new
                        {
                            Id = 60,
                            CreatedBy = "Jane Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 4, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6980), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2023, 5, 20, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6977), new TimeSpan(0, 1, 0, 0, 0)),
                            ModifiedBy = "John Doe",
                            OrderId = 58,
                            Price = 241m,
                            ProductId = 2,
                            Quantity = 128
                        });
                });

            modelBuilder.Entity("TWMS.Domain.Models.Product.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProductionCost")
                        .HasColumnType("money");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("RetailPricePerUnit")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("TWMS.Domain.Models.Product.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("InventoryId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 27, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6109), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Water in sachets",
                            Name = "pure water"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2023, 5, 27, 23, 19, 13, 596, DateTimeKind.Unspecified).AddTicks(6116), new TimeSpan(0, 1, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Water in bottle",
                            Name = "bottle water"
                        });
                });

            modelBuilder.Entity("TWMS.Domain.Models.Staff.Guarantor", b =>
                {
                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<Guid?>("GuarantorAddressStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("StaffId");

                    b.HasIndex("GuarantorAddressStaffId");

                    b.ToTable("Guarantor");
                });

            modelBuilder.Entity("TWMS.Domain.Models.Staff.GuarantorAddress", b =>
                {
                    b.Property<Guid>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AreaLocality")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BuildingNumber")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Landmark")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("State_Province")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StreetName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Zip_PostalCode")
                        .HasColumnType("int");

                    b.HasKey("StaffId");

                    b.ToTable("GuarantorAddress");
                });

            modelBuilder.Entity("TWMS.Domain.Models.Staff.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int?>("JobTitleId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("money");

                    b.Property<Guid?>("StaffAddressStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StaffAddressStaffId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("TWMS.Domain.Models.Staff.StaffAddress", b =>
                {
                    b.Property<Guid>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AreaLocality")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BuildingNumber")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Landmark")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("State_Province")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StreetName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Zip_PostalCode")
                        .HasColumnType("int");

                    b.HasKey("StaffId");

                    b.ToTable("StaffAddresses");
                });

            modelBuilder.Entity("TWMS.Domain.Models.Customer.Customers", b =>
                {
                    b.HasOne("TWMS.Domain.Models.Customer.CustomerAddress", "CustomerAddress")
                        .WithMany("Customers")
                        .HasForeignKey("CustomerAddressCustomerId");

                    b.Navigation("CustomerAddress");
                });

            modelBuilder.Entity("TWMS.Domain.Models.Order.Order", b =>
                {
                    b.HasOne("TWMS.Domain.Models.Customer.Customers", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TWMS.Domain.Models.Order.OrderItem", b =>
                {
                    b.HasOne("TWMS.Domain.Models.Customer.Customers", null)
                        .WithMany("Orders")
                        .HasForeignKey("CustomersId");

                    b.HasOne("TWMS.Domain.Models.Order.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");

                    b.HasOne("TWMS.Domain.Models.Product.ProductType", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TWMS.Domain.Models.Product.ProductType", b =>
                {
                    b.HasOne("TWMS.Domain.Models.Product.Inventory", null)
                        .WithMany("Products")
                        .HasForeignKey("InventoryId");
                });

            modelBuilder.Entity("TWMS.Domain.Models.Staff.Guarantor", b =>
                {
                    b.HasOne("TWMS.Domain.Models.Staff.GuarantorAddress", "GuarantorAddress")
                        .WithMany("Guarantors")
                        .HasForeignKey("GuarantorAddressStaffId");

                    b.HasOne("TWMS.Domain.Models.Staff.Staff", null)
                        .WithOne("Guarantor")
                        .HasForeignKey("TWMS.Domain.Models.Staff.Guarantor", "StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuarantorAddress");
                });

            modelBuilder.Entity("TWMS.Domain.Models.Staff.Staff", b =>
                {
                    b.HasOne("TWMS.Domain.Models.Staff.StaffAddress", "StaffAddress")
                        .WithMany("Staff")
                        .HasForeignKey("StaffAddressStaffId");

                    b.Navigation("StaffAddress");
                });

            modelBuilder.Entity("TWMS.Domain.Models.Customer.CustomerAddress", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("TWMS.Domain.Models.Customer.Customers", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TWMS.Domain.Models.Order.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("TWMS.Domain.Models.Product.Inventory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TWMS.Domain.Models.Staff.GuarantorAddress", b =>
                {
                    b.Navigation("Guarantors");
                });

            modelBuilder.Entity("TWMS.Domain.Models.Staff.Staff", b =>
                {
                    b.Navigation("Guarantor");
                });

            modelBuilder.Entity("TWMS.Domain.Models.Staff.StaffAddress", b =>
                {
                    b.Navigation("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
